name: Inventory Service CI
on:
  push:
    paths:
      - 'inventory-service/**'
      - '.github/workflows/inventory-service.yml' 
  pull_request:
    paths:
      - 'inventory-service/**'
      - '.github/workflows/inventory-service.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: inventory-service
    steps:
      - name: print variable
        run: |
          echo "$GITHUB_ENV"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          context: ./inventory-service
          file: ./inventory-service/dockerfile
          tags: velantechlab/inventory-service:latest