name: Inventory Service CI
on:
  push:
    paths:
      - 'inventory-service/**'
      - '.github/workflows/inventory-service.yml' 
  pull_request:
    paths:
      - 'inventory-service/**'
      - '.github/workflows/inventory-service.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: inventory-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run command
        run: |
            ls -la
      - name: run command1
        run: |
            ls -la
      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          file: ./dockerfile
          push: true
          tags: velantechlab/inventory-service:latest     