name: Inventory Service CI
on:
  push:
    paths:
      - 'inventory-service/**'
      - '.github/workflows/inventory-service.yml' 
  pull_request:
    paths:
      - 'inventory-service/**'
      - '.github/workflows/inventory-service.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        run : |
           ls -la