name: Inventory Service CI
on:
  push:
    paths:
      - 'inventory-service/**'
      - '.github/workflows/inventory-service.yml' 
  pull_request:
    paths:
      - 'inventory-service/**'
      - '.github/workflows/inventory-service.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Inventory Service
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: create git tag
        run : |
          # Fetch all tags to ensure accurate versioning
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          major=$(echo $latest_tag | cut -d'.' -f1 | tr -d 'v')
          minor=$(echo $latest_tag | cut -d'.' -f2)
          patch=$(echo $latest_tag | cut -d'.' -f3)

          new_patch=$((patch + 1))
          new_tag="v$major.$minor.$new_patch"

          echo "Latest tag: $latest_tag"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          context: ./inventory-service
          file: ./inventory-service/dockerfile
          tags: velantechlab/inventory-service:latest
      - name: print env
        run : |
           env | sort
           ls -a
           echo "$GITHUB_OUTPUT"
      