
# Build stage
FROM maven:3.8.7-openjdk-18-slim AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Run stage
#docker pull eclipse-temurin:17-jre
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/inventory-1.0.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
EXPOSE 8080


